""" DISPONIVEL

Revision ID: 3bfdf7e37ef9
Revises: 5f5fab9fc554
Create Date: 2023-04-11 14:36:27.861266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bfdf7e37ef9'
down_revision = '5f5fab9fc554'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filmes', sa.Column('disponivel', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'filmes', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'filmes', type_='foreignkey')
    op.drop_column('filmes', 'disponivel')
    # ### end Alembic commands ###
