"""default em false

Revision ID: 428382629d88
Revises: ba9ec44f0864
Create Date: 2023-04-12 10:54:29.170783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428382629d88'
down_revision = 'ba9ec44f0864'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'filmes', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'filmes', type_='foreignkey')
    # ### end Alembic commands ###
