"""Chave estrangeira

Revision ID: 5f5fab9fc554
Revises: 58b436905595
Create Date: 2023-04-06 13:41:36.768074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5fab9fc554'
down_revision = '58b436905595'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filmes', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'filmes', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'filmes', type_='foreignkey')
    op.drop_column('filmes', 'usuario_id')
    # ### end Alembic commands ###
