"""default em aluguel

Revision ID: ba9ec44f0864
Revises: bfef295569dd
Create Date: 2023-04-12 10:52:01.985209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9ec44f0864'
down_revision = 'bfef295569dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'filmes', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'filmes', type_='foreignkey')
    # ### end Alembic commands ###
