"""Adicionando aluguel

Revision ID: bfef295569dd
Revises: 3bfdf7e37ef9
Create Date: 2023-04-12 10:28:00.624177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfef295569dd'
down_revision = '3bfdf7e37ef9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluguel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra', sa.Boolean(), nullable=True),
    sa.Column('dias', sa.Integer(), nullable=True),
    sa.Column('qualidade', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('filme_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], name='fk_aluguel_filme'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='fk_aluguel_usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aluguel_id'), 'aluguel', ['id'], unique=False)
    op.create_foreign_key(None, 'filmes', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'filmes', type_='foreignkey')
    op.drop_index(op.f('ix_aluguel_id'), table_name='aluguel')
    op.drop_table('aluguel')
    # ### end Alembic commands ###
